input {
  tcp {
    port => 5002
    codec => json
  }
}

filter {
  # Если это не JSON или нет поля event - отбрасываем
  if "_jsonparsefailure" in [tags] or ![event] {
    drop { }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "secure-bank-logs-%{+YYYY.MM.dd}"
  }
}
